debug:
  enabled: True
  server:
    host: belfry.com
    port: 8001
flask:
  init:
    import_name: epubber
  secret_key: gMbicGWXQe5N1yVmr5wpiDjgohaVkQEh3dmHJRSWIk
  SESSION_COOKIE_SECURE: True
  config:
    SESSION_COOKIE_SECURE: True
  sessions_path: sessions
  sessions_timeout: 3600
views: [epubber.views.main]
logging:
  version: 1
  formatters:
    default:
      format: '%(asctime)s.%(msecs).03d: %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    accesslog:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: /var/log/epubber/epubber_access.log
      maxBytes: 10485760
      backupCount: 3
    errorlog:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: /var/log/epubber/epubber_errors.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    epubber_access:
      level: INFO
      propagate: 0
      handlers: [accesslog]
    epubber_error:
      level: DEBUG
      propagate: 0
      handlers: [errorlog]

